name: Common Web Starter

on:
  push:
    paths:
      - common-web-starter/**
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - common-web-starter/**

jobs:
  run-integration-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: echo $GITHUB_WORKSPACE
      - name: Decrypt settings.xml
        run: gpg --quiet --batch --yes --decrypt --passphrase="$MAVEN_SETTINGS_GPG_AES_256_KEY" --output "$GITHUB_WORKSPACE/maven-settings/settings.xml" "$GITHUB_WORKSPACE/maven-settings/settings.xml.gpg"
      - name: Build with Maven
        run: |
          cd common-web-starter
          pwd
          mvn --batch-mode --update-snapshots -s "$GITHUB_WORKSPACE/maven-settings/settings.xml" clean verify


