name: Common Web Starter

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
    paths:
      - common-web-starter/**

jobs:
  run-integration-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots package
      - run: echo $(pwd)


