name: ALWAYS FAIL

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: agilepathway/label-checker@v1.0.113
        with:
          all_of: "DO NOT MERGE"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
      - name: FAIL
        run: exit 1

