name: Multitenancy Base Starter Workflow

path-ant-matcher: &path-ant-matcher "multitenancy-spring-boot-starter-base/**"
path-matcher: &path-matcher "multitenancy-spring-boot-starter-base/"


on:
  push:
    paths:
      - *path-ant-matcher

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - run: echo $GITHUB_WORKSPACE
      - name: Decrypt settings.xml
        run: gpg --quiet --batch --yes --decrypt --passphrase="$MAVEN_SETTINGS_GPG_AES_256_KEY" --output "$GITHUB_WORKSPACE/maven-settings/settings.xml" "$GITHUB_WORKSPACE/maven-settings/settings.xml.gpg"
        env:
          MAVEN_SETTINGS_GPG_AES_256_KEY: ${{ secrets.MAVEN_SETTINGS_GPG_AES_256_KEY }}
      - name: Build with Maven
        run: |
          cd ${PATH}
          pwd
          ./mvnw --batch-mode --update-snapshots -s "$GITHUB_WORKSPACE/maven-settings/settings.xml" clean verify
        env:
          PATH: *path-matcher

