name: Multitenancy Base Starter Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
    paths:
      - multitenancy-spring-boot-starter-base/**

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$GITHUB_WORKSPACE"

