name: Multitenancy Base Starter Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - multitenancy-spring-boot-starter-base/**

jobs:
  multitenancy-basse-starter-run-integration-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$GITHUB_WORKSPACE"

