name: Multitenancy Base Starter Workflow

on:
  push:
    paths:
      - multitenancy-spring-boot-starter-base/**

jobs:
  multitenancy-basse-starter-run-integration-test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "$GITHUB_WORKSPACE"

